<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>  
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Enums\" />
    <Folder Include="Events\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Duende.IdentityServer" Version="7.2.3" />
    <PackageReference Include="Duende.IdentityServer.AspNetIdentity" Version="7.2.3" />
    <PackageReference Include="FluentResults" Version="3.16.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SIADG.Toolkit\SIADG.Toolkit.csproj" />
  </ItemGroup>

</Project>
